language: cpp

addons:
  apt_packages:
    - libgl1-mesa-dev
    - xorg-dev
    - libxcb-render-util0-dev
    - libxcb-xkb-dev
    - libxcb-icccm4-dev
    - libudev-dev
    - libfreetype6-dev
    - libxcb-image0-dev
    - libxcb-keysyms1-dev
    - libxcb-xinerama0-dev

before_script:
- mkdir build && cd build
- conan --version
- conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
- conan install .. -s build_type=${CONFIG} --build missing
- cmake .. -DCMAKE_BUILD_TYPE=${CONFIG} -DUNIT_TEST=ON

script:
- cmake --build .
- ctest -VV -C ${CONFIG} --schedule-random --output-on-failure

matrix:
  include:

  # - name: "macOS Xcode 10 Debug"
  #   os: osx
  #   compiler: clang
  #   osx_image: xcode10
  #   install:
  #     - pip install conan
  #   env:
  #     - CONFIG=Debug

  # - name: "macOS Xcode 10 Release"
  #   os: osx
  #   compiler: clang
  #   osx_image: xcode10
  #   install:
  #     - pip install conan
  #   env:
  #     - CONFIG=Release

  # - name: "Linux gcc Debug"
  #   os: linux
  #   dist: bionic
  #   compiler: gcc
  #   install:
  #     - pip install conan
  #   env:
  #     - CONFIG=Debug

  # - name: "Linux gcc Release"
  #   os: linux
  #   dist: bionic
  #   compiler: gcc
  #   install:
  #     - pip install conan
  #   env:
  #     - CONFIG=Release

  - name: "Windows Visual studio 15 2017 Debug"
    os: windows
    compiler: msvc
    before_install:
      # python and conan installation
      - choco install python3 --params "/InstallDir:C:\\Python"
      - choco install -y visualstudio2019community visualstudio2019-workload-nativedesktop
  #        - choco install -y visualstudio2019buildtools
      - export PATH="/c/Python:/c/Python/Scripts:/c/Users/travis/AppData/Roaming/Python/Python38/Scripts:$PATH"
      - pip3 install --user --upgrade conan
      - conan user
      - conan profile new default --detect
      - conan profile remove settings.compiler.libcxx default
      - conan profile update settings.compiler="Visual Studio" default
      - conan profile update settings.compiler.version=15 default # Visual Studio 2017
  #        - conan profile update settings.compiler.cppstd=20 default
      - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    env:
      - CONFIG=Debug

  # - name: "Windows Visual studio 15 2017 Release"
  #   os: windows
  #   install:
  #     - choco install -y python '"/InstallDir:C:\\tools\\python3"'
  #     - choco install -y pip
  #     - pip install conan conan_package_tools
  #   env:
  #     - CONFIG=Release

notifications:
  email: false

