language: cpp

addons:
  apt_packages:
    - libgl1-mesa-dev
    - xorg-dev
    - libxcb-render-util0-dev
    - libxcb-xkb-dev
    - libxcb-icccm4-dev
    - libudev-dev
    - libfreetype6-dev
    - libxcb-image0-dev
    - libxcb-keysyms1-dev
    - libxcb-xinerama0-dev

before_script:
- mkdir build && cd build
- conan --version
- conan remote add sfml https://api.bintray.com/conan/bincrafters/public-conan
- conan install .. ${CONAN_SETTINGS_FLAG}
- cmake .. -DCMAKE_BUILD_TYPE=${CONFIG} -DUNIT_TEST=ON ${CMAKE_FLAGS}

script:
- cmake --build .
- ctest -VV -C ${CONFIG} --schedule-random --output-on-failure

matrix:
  include:

  # - name: "macOS Xcode 10 Debug"
  #   os: osx
  #   compiler: clang
  #   osx_image: xcode10
  #   install:
  #     - pip install conan
  #   env:
  #     - CONFIG=Debug

  # - name: "macOS Xcode 10 Release"
  #   os: osx
  #   compiler: clang
  #   osx_image: xcode10
  #   install:
  #     - pip install conan
  #   env:
  #     - CONFIG=Release

  - name: "Windows Visual studio 15 2017 Debug"
    os: windows
    install:
      - choco install conan
      - export PATH="/c/Program Files/Conan/conan:$PATH"
      - conan profile new default --detect
    env:
      - CONFIG=Debug
      # - CONAN_FLAGS="-s compiler='Visual Studio' -s compiler.version=15 -s arch=x8
      - CONAN_SETTINGS_FLAG="-g cmake -s build_type=Release -s compiler.libcxx=libstdc++11 -b missing"
      - CMAKE_FLAGS="-G \"Visual Studio 15 2017 Win64\" -DCMAKE_GENERATOR_PLATFORM=x64"

  # - name: "Windows Visual studio 15 2017 Release"
  #   os: windows
  #   install:
  #     - choco install conan
  #     - export PATH="/c/Program Files/Conan/conan:$PATH"
  #     - conan profile new default --detect
  #   env:
  #     - CONFIG=Release
  #     - CONAN_FLAGS="-s compiler='Visual Studio' -s compiler.version=15 -s arch=x86_64"
  #     - CMAKE_FLAGS="-G \"Visual Studio 15 2017 Win64\" -DCMAKE_GENERATOR_PLATFORM=x64"

  # - name: "Linux gcc Debug"
  #   os: linux
  #   dist: bionic
  #   compiler: gcc
  #   install:
  #     - pip install conan
  #   env:
  #     - CONFIG=Debug

  # - name: "Linux gcc Release"
  #   os: linux
  #   dist: bionic
  #   compiler: gcc
  #   install:
  #     - pip install conan
  #   env:
  #     - CONFIG=Release

notifications:
  email: false

